### ISSUE TITLE
Please provide builds for download

### ISSUE THREAD

**Issue by probonopd** [AlexandruIstrate/ExeQt#1]
Please provide builds for download on GitHub Releases, especially the AppImage for Linux. Thank you very much.

**Comment by AlexandruIstrate** [comment]
Hello,
I have successfully bundled my app into an AppImage and later today I will upload it to the release page of my repository. I will also be compiling a version for Windows in the following days. As for macOS: I don't have a Mac yet.
Thanks for the great work on linuxdeployqt!

**Comment by probonopd** [comment]
Thanks. Please ping me once the AppImage is on GitHub Releases, so that I can include it in the AppImageHub central directory of available AppImages.

**Comment by AlexandruIstrate** [comment]
Hello,
Version 1.2 of ExeQt has just been released. Check it out!
[ExeQt Releases](https://github.com/AlexandruIstrate/ExeQt/releases)

**Comment by probonopd** [comment]
Thank you very much @AlexandruIstrate. How did you produce this build? Unfortunately it does not run on Ubuntu 14.04 (the oldest still-supported version): `AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-9905/AppRun)`

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems and please build e.g., on Ubuntu 14.04.

**Comment by AlexandruIstrate** [comment]
Thank you for testing.
I only tested on 18.04 LTS (the newest version) using Qt 5.10.1. I will be gone out of town until the end of the week but when I come back I will test it on older Ubuntu versions. Thank you for the link about deploying AppImages. It will come in helpful. I saw that it says you should compile it on the oldest system you want it to run on. I will be compiling it on Ubuntu 14.04 LTS in a VM.

**Comment by probonopd** [comment]
> I will be compilin it on Ubuntu 14.04 LTS in a VM.

Thank you very much. That should do.

**Comment by AlexandruIstrate** [comment]
I built the project and made the AppImage in an Ubuntu 14.04.5 LTS virtual machine. I also tested the AppImage on a fresh install of 14.04.5 without installing Qt or anything else. Now it seems to work both on 14.04.5 and on the new 18.04.
